name: Update sing-box PuerNya
on:
  workflow_dispatch:
  schedule:
    - cron: "38 14 * * *"
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - ".github/workflows"

jobs:
  go:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.go.outputs.version }}
    steps:
      - name: Get `Go` latest version
        id: go
        run: |
          echo version=$(curl -sSL https://raw.githubusercontent.com/actions/go-versions/update-versions-manifest-file/versions-manifest.json | grep '"version"' | head -1 | awk -F'"' '{print $4}') >> $GITHUB_OUTPUT

  sing-box:
    runs-on: ubuntu-latest
    needs: go
    outputs:
      version: ${{ steps.sing-box.outputs.version }}
      tags: ${{ steps.sing-box.outputs.tags }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: PuerNya/sing-box
          ref: building
          fetch-depth: 0

      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ needs.go.outputs.version }}

      - name: Get `sing-box` version
        id: sing-box
        run: |
          git remote add sekai https://github.com/SagerNet/sing-box.git
          git fetch --tags sekai
          version=$(CGO_ENABLED=0 go run ./cmd/internal/read_tag)
          echo version=$version >> $GITHUB_OUTPUT
          echo tags=with_quic,with_shadowsocksr,with_ech,with_utls,with_clash_api >> $GITHUB_OUTPUT

  cross:
    strategy:
      matrix:
        include:
          # linux
          - name: linux-amd64
            goos: linux
            goarch: amd64
            goamd64: v1
          - name: linux-amd64-v3
            goos: linux
            goarch: amd64
            goamd64: v3
          - name: linux-arm64
            goos: linux
            goarch: arm64

      fail-fast: false
    runs-on: ubuntu-latest
    needs:
      - go
      - sing-box
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      GOAMD64: ${{ matrix.goamd64 }}
      GOARM: ${{ matrix.goarm }}
      GOMIPS: ${{ matrix.gomips }}
      CGO_ENABLED: 0
      TAGS: ${{ needs.sing-box.outputs.tags }}
      VERSION: ${{ needs.sing-box.outputs.version }}
    steps:
      - name: Checkout sing-box
        uses: actions/checkout@v4
        with:
          repository: PuerNya/sing-box
          ref: building
          fetch-depth: 1

      - name: Setup `Go`
        uses: actions/setup-go@v5
        with:
          go-version: ${{ needs.go.outputs.version }}

      - name: Checkout sing repository
        uses: actions/checkout@v4
        with:
          repository: PuerNya/sing
          ref: building
          path: sing

      - name: Build core
        id: build
        run: go build -v -trimpath -ldflags "-X 'github.com/sagernet/sing-box/constant.Version=${VERSION}' -s -w -buildid=" -tags "${TAGS}" ./cmd/sing-box

      - name: Upload files to workspace
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path:
            sing-box*
          compression-level: 9

  push_puernya:
    needs:
      - cross
      - sing-box
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ needs.sing-box.outputs.version }}
    steps:
      - name: Clone Repository
        uses: actions/checkout@main

      - name: Download files from workspace
        uses: actions/download-artifact@v4
        with:
          path: ./tmp/

      - name: Zip core by `tar`
        run: |
          archs=(amd64 amd64-v3 arm64)
          new_name=(amd64 amd64v3 armv8)
          for((i=0;i<9;i++));do
            mv -f ./tmp/linux-${archs[i]}/sing-box ./tmp/CrashCore
            chmod +x ./tmp/CrashCore
            tar --no-same-owner -czf ./tmp/sing-box-linux-${new_name[i]}.tar.gz -C ./tmp/ ./CrashCore
          done

      - name: Move files
        run: |
          mkdir -p ./sing-box-puernya/
          rm -rf ./sing-box-puernya/*
          mv -f ./tmp/sing-box-linux* ./sing-box-puernya/
          rm -rf ./tmp* 

      # - name: Commit and push `sing-box`
      #   run: |
      #     cd ./sing-box-puernya/ || exit 1
      #     git config --global user.email "github-actions[bot]@users.noreply.github.com"
      #     git config --global user.name "github-actions[bot]"
      #     git add . && git commit -m "更新 sing-box 内核 PuerNya 版至 v${VERSION}" || exit 0
      #     git push -f
